### PR TITLE
fix: performance issue in nvidia_gpu_stats

### LINKED ISSUE #8359: [Bug]: nvidia_gpu_stats binary causes high CPU cycle usage.
### Describe the bug

Using the new backend with:

```
import wandb
wandb.require("core")
```

WandB spawns a `nvidia_gpu_stats` process that has a very high CPU usage. This should not happen!

Launching an 8GPU  job and running `top` shows the following:

```
Tasks:  58 total,   1 running,  57 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.6 us,  3.6 sy,  0.0 ni, 95.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 1886814.+total, 1015482.+free,  17659.7 used, 853672.1 buff/cache
top - 10:38:28 up 43 days, 22:19,  2 users,  load average: 24.18, 26.19, 21.18
Tasks: 281 total,   1 running, 280 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us, 29.1 sy,  0.9 ni, 69.5 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem : 1886814.+total, 931970.9 free,  39175.9 used, 915667.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 1775770.+avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                               
 711417 root      35  15 6721488 377724   6784 S  5907   0.0  11:15.03 nvidia_gpu_stat                                                                                       
 709541 root      35  15  295.4g   8.8g   8.0g S  42.4   0.5   0:12.62 ray::_RayTrainW                                                                                       
 709539 root      35  15  295.4g   8.8g   8.0g S  37.7   0.5   0:12.60 ray::_RayTrainW                                                                                       
 709532 root      35  15  295.5g   8.8g   8.0g S  34.8   0.5   0:12.41 ray::_RayTrainW                                                                                       
 709529 root      35  15  296.0g   8.8g   8.0g S  34.1   0.5   0:13.55 ray::_RayTrainW                                                                                       
 709538 root      35  15  295.4g   8.8g   8.0g S  32.8   0.5   0:12.44 ray::_RayTrainW                                                                                       
 709534 root      35  15  295.5g   8.8g   8.0g S  32.1   0.5   0:12.43 ray::_RayTrainW                                                                                       
 709535 root      35  15  295.5g   8.8g   8.0g S  31.1   0.5   0:11.86 ray::_RayTrainW                                                                                       
 709533 root      35  15  295.5g   8.8g   8.0g S  30.1   0.5   0:12.34 ray::_RayTrainW  
 ```
 
 
I can reproduce that without even import wandb, e.g.:

```
watch /opt/conda/lib/python3.10/site-packages/wandb/bin/nvidia_gpu_stats 
```

### PR DESCRIPTION
**Pull request by dmitryduev**
Description
-----------

- Fixes WB-20875
- Fixes #8359

In this PR: 
- Lighter-weight way to discover process's descendants on linux
- Track feature/query availability for the devices

- [x] I updated CHANGELOG.md, or it's not applicable

Testing
-------
How was this PR tested?

### CODE REVIEW

File: core/pkg/monitor/gpu_nvidia.go [hunk 1]
```diff
@@ -256,7 +256,7 @@ func (g *GPUNvidia) Probe() *spb.MetadataRequest {
 
 		cudaCores := fmt.Sprintf("_gpu.%d.cudaCores", di)
 		if v, ok := g.sample[cudaCores]; ok {
-			if v, ok := v.(float64); ok {
+			if v, ok := v.(float64); ok && v > 0 {
```
Comment (kptkin) [inline core/pkg/monitor/gpu_nvidia.go:259]: maybe worth a comment about the zero value

File: nvidia_gpu_stats/src/gpu_nvidia.rs [hunk 2]
```diff
@@ -57,15 +143,23 @@ impl NvidiaGpu {
...
-        sys.processes()
-            .values()
-            .filter(|process| process.parent() == Some(Pid::from(pid as usize)))
-            .map(|process| process.pid().as_u32() as i32)
-            .collect()
+    fn get_child_pids(&self, parent_pid: i32) -> Result<Vec<i32>, std::io::Error> {
+        let mut descendant_pids = Vec::new();
+        let mut stack = vec![parent_pid];
+
+        while let Some(pid) = stack.pop() {
```
Comment (kptkin) [inline nvidia_gpu_stats/src/gpu_nvidia.rs:150]: edge case: but should we care about potential loops?

**Review by kptkin — APPROVED** [review]
